name: markdownlint

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (latest LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install markdownlint-cli
        run: npm install --global markdownlint-cli

      - name: Run markdownlint
        run: markdownlint "**/*.md"
